export const USER_FETCH_BEGIN = 'USER_FETCH_BEGIN';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILURE = 'USER_FETCH_FAILURE';
export const USER_CLEAR = 'USER_CLEAR';
export const REPORTS_FETCH_BEGIN = 'REPORTS_FETCH_BEGIN';
export const REPORTS_FETCH_SUCCESS = 'REPORTS_FETCH_SUCCESS';
export const REPORTS_FETCH_FAILURE = 'REPORTS_FETCH_FAILURE';
export const REPORTS_CLEAR = 'REPORTS_CLEAR';